version: '3'

services:
  butgg:
    image: mbrother2/backuptogoogle
    container_name: butgg
    environment:
      - GG_CLIENT_ID=xxxxxx
      - GG_CLIENT_SECRET=xxxxxx
      - BACKUP_DIR=/root/backup
      - TAR_BEFORE_UPLOAD=No
      - SYNC_FILE=No
      - DAY_REMOVE=7
      - GDRIVE_ID=None
      - EMAIL_USER=None
      - EMAIL_PASS=None
      - EMAIL_TO=None
    command: cron
    volumes:
      - /root/gdrive:/root/bin
      - /root/conf:/root/.gdrive
      - /root:/root/backup # Directory in container must same BACKUP_DIR
    restart: always
